[2024-03-11 16:45:28,858: INFO: main: welcome to our logs]
[2024-03-13 14:21:45,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:21:45,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:21:45,341: INFO: common: created directory at: artifacts]
[2024-03-13 14:54:16,073: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:54:16,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:54:16,073: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:54:16,073: INFO: common: created directory at: artifacts]
[2024-03-13 14:54:16,073: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2024-03-13 14:57:22,393: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:57:22,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:57:22,408: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:57:22,408: INFO: common: created directory at: artifacts]
[2024-03-13 14:57:22,408: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 14:57:22,408: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 14:57:54,939: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:57:54,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:57:54,955: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:57:54,955: INFO: common: created directory at: artifacts]
[2024-03-13 14:57:54,955: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 14:57:54,955: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 15:02:08,926: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:02:08,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:02:08,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:02:08,926: INFO: common: created directory at: artifacts]
[2024-03-13 15:02:08,926: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:02:08,926: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 15:06:28,036: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:06:28,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:06:28,036: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:06:28,036: INFO: common: created directory at: artifacts]
[2024-03-13 15:06:28,036: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:06:28,036: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:06:28,036: ERROR: main: download() got an unexpected keyword argument 'prefix']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix=file_id)
TypeError: download() got an unexpected keyword argument 'prefix'
[2024-03-13 15:08:51,083: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:08:51,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:08:51,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:08:51,098: INFO: common: created directory at: artifacts]
[2024-03-13 15:08:51,098: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:08:51,098: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:09:38,764: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-13 15:09:38,787: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 37, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\USER\anaconda3\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\USER\anaconda3\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-03-13 15:50:48,121: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:50:48,129: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:50:48,129: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:50:48,129: INFO: common: created directory at: artifacts]
[2024-03-13 15:50:48,129: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:50:48,133: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:51:31,821: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-13 15:51:32,660: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
