[2024-03-11 16:45:28,858: INFO: main: welcome to our logs]
[2024-03-13 14:21:45,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:21:45,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:21:45,341: INFO: common: created directory at: artifacts]
[2024-03-13 14:54:16,073: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:54:16,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:54:16,073: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:54:16,073: INFO: common: created directory at: artifacts]
[2024-03-13 14:54:16,073: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2024-03-13 14:57:22,393: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:57:22,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:57:22,408: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:57:22,408: INFO: common: created directory at: artifacts]
[2024-03-13 14:57:22,408: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 14:57:22,408: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 14:57:54,939: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 14:57:54,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 14:57:54,955: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 14:57:54,955: INFO: common: created directory at: artifacts]
[2024-03-13 14:57:54,955: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 14:57:54,955: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 15:02:08,926: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:02:08,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:02:08,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:02:08,926: INFO: common: created directory at: artifacts]
[2024-03-13 15:02:08,926: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:02:08,926: ERROR: main: local variable 'data_ingestion' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
UnboundLocalError: local variable 'data_ingestion' referenced before assignment
[2024-03-13 15:06:28,036: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:06:28,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:06:28,036: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:06:28,036: INFO: common: created directory at: artifacts]
[2024-03-13 15:06:28,036: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:06:28,036: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:06:28,036: ERROR: main: download() got an unexpected keyword argument 'prefix']
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix=file_id)
TypeError: download() got an unexpected keyword argument 'prefix'
[2024-03-13 15:08:51,083: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:08:51,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:08:51,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:08:51,098: INFO: common: created directory at: artifacts]
[2024-03-13 15:08:51,098: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:08:51,098: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:09:38,764: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1_y7Yhg9ozIO6OyKP8lZEeGGa3NEz1iut/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-13 15:09:38,787: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 37, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\USER\anaconda3\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\USER\anaconda3\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-03-13 15:50:48,121: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-13 15:50:48,129: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 15:50:48,129: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 15:50:48,129: INFO: common: created directory at: artifacts]
[2024-03-13 15:50:48,129: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 15:50:48,133: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-13 15:51:31,821: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-13 15:51:32,660: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:15:01,360: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-14 12:15:01,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:15:01,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:15:01,385: INFO: common: created directory at: artifacts]
[2024-03-14 12:15:01,385: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 12:15:01,389: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-14 12:15:45,027: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-14 12:15:46,418: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:15:46,418: INFO: main: ***************]
[2024-03-14 12:15:46,418: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:15:46,418: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:15:46,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:15:46,438: INFO: common: created directory at: artifacts]
[2024-03-14 12:15:46,438: ERROR: main: name 'get_prepare_base_model_config' is not defined]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 13, in main
    prepare_base_model_config = config,get_prepare_base_model_config()
NameError: name 'get_prepare_base_model_config' is not defined
[2024-03-14 12:18:25,342: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-14 12:18:25,358: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:18:25,358: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:18:25,358: INFO: common: created directory at: artifacts]
[2024-03-14 12:18:25,367: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 12:18:25,368: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-14 12:19:22,085: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-14 12:19:23,339: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:19:23,347: INFO: main: ***************]
[2024-03-14 12:19:23,347: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:19:23,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:19:23,357: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:19:23,359: INFO: common: created directory at: artifacts]
[2024-03-14 12:19:23,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:19:23,361: ERROR: main: __init__() got an unexpected keyword argument 'Params_weights']
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'Params_weights'
[2024-03-14 12:21:13,541: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-14 12:21:13,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:21:13,541: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:21:13,541: INFO: common: created directory at: artifacts]
[2024-03-14 12:21:13,554: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 12:21:13,555: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-14 12:21:56,027: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-14 12:21:57,725: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:21:57,725: INFO: main: ***************]
[2024-03-14 12:21:57,725: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:21:57,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:21:57,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:21:57,736: INFO: common: created directory at: artifacts]
[2024-03-14 12:21:57,736: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:21:57,736: ERROR: main: 'ConfigurationManager' object has no attribute 'prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 14, in main
    prepare_base_model = prepareBaseModel(config.prepare_base_model_config)
AttributeError: 'ConfigurationManager' object has no attribute 'prepare_base_model_config'
[2024-03-14 12:24:41,500: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-14 12:24:41,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:24:41,515: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:24:41,515: INFO: common: created directory at: artifacts]
[2024-03-14 12:24:41,520: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 12:24:41,521: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-14 12:25:21,836: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-14 12:25:23,045: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:25:23,045: INFO: main: ***************]
[2024-03-14 12:25:23,045: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:25:23,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:25:23,058: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:25:23,058: INFO: common: created directory at: artifacts]
[2024-03-14 12:25:23,059: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:25:23,060: ERROR: main: 'ConfigurationManager' object has no attribute 'prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 14, in main
    prepare_base_model = prepareBaseModel(config.prepare_base_model_config)
AttributeError: 'ConfigurationManager' object has no attribute 'prepare_base_model_config'
[2024-03-14 12:27:12,761: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-14 12:27:12,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:27:12,778: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:27:12,780: INFO: common: created directory at: artifacts]
[2024-03-14 12:27:12,782: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 12:27:12,784: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-14 12:27:49,286: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-14 12:27:50,808: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-14 12:27:50,808: INFO: main: ***************]
[2024-03-14 12:27:50,808: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:27:50,818: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:27:50,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:27:50,830: INFO: common: created directory at: artifacts]
[2024-03-14 12:27:50,833: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:27:50,834: ERROR: main: 'ConfigurationManager' object has no attribute 'prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 14, in main
    prepare_base_model = prepareBaseModel(config.prepare_base_model_config)
AttributeError: 'ConfigurationManager' object has no attribute 'prepare_base_model_config'
[2024-03-14 12:35:45,888: INFO: main: ***************]
[2024-03-14 12:35:45,888: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:35:45,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:35:45,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:35:45,888: INFO: common: created directory at: artifacts]
[2024-03-14 12:35:45,901: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:35:45,908: ERROR: main: The `weights` argument should be either `None` (random initialization), `imagenet` (pre-training on ImageNet), or the path to the weights file to be loaded.  Received: weights=Imagenet]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_02_Prepare_base_model.py", line 15, in main
    prepare_base_model.get_base_model()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\prepare_base_model.py", line 13, in get_base_model
    self.model = tf.keras.applications.vgg16.VGG16(
  File "C:\Users\USER\anaconda3\envs\kidney\lib\site-packages\keras\applications\vgg16.py", line 122, in VGG16
    raise ValueError(
ValueError: The `weights` argument should be either `None` (random initialization), `imagenet` (pre-training on ImageNet), or the path to the weights file to be loaded.  Received: weights=Imagenet
[2024-03-14 12:38:32,088: INFO: main: ***************]
[2024-03-14 12:38:32,088: INFO: main: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-14 12:38:32,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 12:38:32,103: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 12:38:32,105: INFO: common: created directory at: artifacts]
[2024-03-14 12:38:32,105: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 12:38:34,176: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 12:38:34,787: INFO: main: >>>>> stage Prepare Base Model Stage completed <<<<<

x=========x]
[2024-03-14 15:46:38,972: INFO: main: **************]
[2024-03-14 15:46:38,972: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 15:46:38,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 15:46:39,007: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 15:46:39,010: INFO: common: created directory at: artifacts]
[2024-03-14 15:46:39,010: ERROR: main: expected str, bytes or os.PathLike object, not list]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 14, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 54, in get_training_config
    Path([training.root_dir])
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
[2024-03-14 16:13:49,812: INFO: main: **************]
[2024-03-14 16:13:49,812: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:13:49,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:13:49,820: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:13:49,820: INFO: common: created directory at: artifacts]
[2024-03-14 16:13:49,826: ERROR: main: expected str, bytes or os.PathLike object, not list]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 14, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 54, in get_training_config
    Path([training.root_dir])
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\USER\anaconda3\envs\kidney\lib\pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
[2024-03-14 16:24:23,724: INFO: main: **************]
[2024-03-14 16:24:23,724: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:24:23,734: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:24:23,739: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:24:23,739: INFO: common: created directory at: artifacts]
[2024-03-14 16:24:23,739: ERROR: main: Argument path_to_directories of type <class 'pathlib.WindowsPath'> to <function create_directories at 0x000002C1343F2040> does not match annotation type <class 'list'>]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 14, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 53, in get_training_config
    create_directories(Path(training.root_dir)
  File "C:\Users\USER\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 803, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path_to_directories of type <class 'pathlib.WindowsPath'> to <function create_directories at 0x000002C1343F2040> does not match annotation type <class 'list'>
[2024-03-14 16:28:25,692: INFO: main: **************]
[2024-03-14 16:28:25,707: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:28:25,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:28:25,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:28:25,715: INFO: common: created directory at: artifacts]
[2024-03-14 16:28:25,716: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:28:25,716: ERROR: main: __init__() got an unexpected keyword argument 'updated_base_model']
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 14, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 56, in get_training_config
    training_config = TrainingConfig(
TypeError: __init__() got an unexpected keyword argument 'updated_base_model'
[2024-03-14 16:31:37,679: INFO: main: **************]
[2024-03-14 16:31:37,679: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:31:37,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:31:37,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:31:37,679: INFO: common: created directory at: artifacts]
[2024-03-14 16:31:37,695: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:31:37,696: ERROR: main: __init__() got an unexpected keyword argument 'training_data']
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 14, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 57, in get_training_config
    training_config = TrainingConfig(
TypeError: __init__() got an unexpected keyword argument 'training_data'
[2024-03-14 16:35:36,471: INFO: main: **************]
[2024-03-14 16:35:36,471: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:35:36,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:35:36,511: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:35:36,514: INFO: common: created directory at: artifacts]
[2024-03-14 16:35:36,517: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:35:36,519: ERROR: main: __init__() got an unexpected keyword argument 'training_data']
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training_config = config.get_training_config()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\config\configuration.py", line 57, in get_training_config
    training_config = TrainingConfig(
TypeError: __init__() got an unexpected keyword argument 'training_data'
[2024-03-14 16:39:02,765: INFO: main: **************]
[2024-03-14 16:39:02,765: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:39:02,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:39:02,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:39:02,788: INFO: common: created directory at: artifacts]
[2024-03-14 16:39:02,788: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:39:03,902: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train_valid_generator()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\components\model_training.py", line 34, in train_valid_generator
    self.valid_generator=valid_datagenerator.flow_from_directory(
  File "C:\Users\USER\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\USER\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-03-14 16:41:46,993: INFO: main: **************]
[2024-03-14 16:41:46,993: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:41:47,008: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:41:47,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:41:47,014: INFO: common: created directory at: artifacts]
[2024-03-14 16:41:47,015: INFO: common: created directory at: artifacts\training]
[2024-03-14 16:41:48,040: ERROR: main: train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    obj.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 22, in main
    training.train()
TypeError: train() missing 1 required positional argument: 'callback_list'
[2024-03-14 16:43:03,569: INFO: main: **************]
[2024-03-14 16:43:03,569: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-14 16:43:03,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 16:43:03,569: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 16:43:03,569: INFO: common: created directory at: artifacts]
[2024-03-14 16:43:03,580: INFO: common: created directory at: artifacts\training]
[2024-03-15 10:33:10,979: INFO: main: **************]
[2024-03-15 10:33:10,979: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-15 10:33:10,979: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 10:33:11,010: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 10:33:11,011: INFO: common: created directory at: artifacts]
[2024-03-15 10:33:11,012: INFO: common: created directory at: artifacts\training]
[2024-03-15 11:04:39,700: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 11:04:43,634: INFO: builder_impl: Assets written to: artifacts\training\model.hs\assets]
[2024-03-15 11:04:43,962: INFO: main: >>>>>>>> stage Training Stage completed <<<<<<<<

x==============x]
[2024-03-15 15:22:50,567: INFO: main: **************]
[2024-03-15 15:22:50,567: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-15 15:22:50,567: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:22:50,586: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:22:50,589: INFO: common: created directory at: artifacts]
[2024-03-15 15:22:50,591: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:37:47,868: INFO: main: **************]
[2024-03-15 15:37:47,868: INFO: main: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-15 15:37:47,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 15:37:47,895: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 15:37:47,896: INFO: common: created directory at: artifacts]
[2024-03-15 15:37:47,898: INFO: common: created directory at: artifacts\training]
[2024-03-15 15:57:20,945: INFO: main: >>>>>>>> stage Training Stage completed <<<<<<<<

x==============x]
[2024-03-15 16:16:28,941: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:16:28,961: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:16:28,965: INFO: common: created directory at: artifacts]
[2024-03-15 16:19:37,172: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:19:37,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:19:37,179: INFO: common: created directory at: artifacts]
[2024-03-15 16:20:09,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:20:09,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:20:09,435: INFO: common: created directory at: artifacts]
[2024-03-15 16:22:45,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:22:45,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:22:45,166: INFO: common: created directory at: artifacts]
[2024-03-15 16:27:40,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:27:40,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:27:40,700: INFO: common: created directory at: artifacts]
[2024-03-15 16:28:54,178: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 16:28:56,579: INFO: builder_impl: Assets written to: C:\Users\USER\AppData\Local\Temp\tmp19xdivjc\model\data\model\assets]
[2024-03-15 16:29:17,384: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\3c98276bed034a9c9c557615b8470860\artifacts\model\data]
[2024-03-15 16:29:17,384: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\3c98276bed034a9c9c557615b8470860\artifacts\model\data\model]
[2024-03-15 16:29:17,397: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\3c98276bed034a9c9c557615b8470860\artifacts\model\data\model\assets]
[2024-03-15 16:29:17,413: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\3c98276bed034a9c9c557615b8470860\artifacts\model\data\model\variables]
[2024-03-15 16:32:32,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:32:32,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:32:32,667: INFO: common: created directory at: artifacts]
[2024-03-15 16:34:00,885: INFO: common: json file saved at: scores.json]
[2024-03-15 16:34:05,080: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-15 16:34:07,378: INFO: builder_impl: Assets written to: C:\Users\USER\AppData\Local\Temp\tmp7holcxwx\model\data\model\assets]
[2024-03-15 16:34:23,648: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\94b0612e8e834d7ea958090ce6bf29ef\artifacts\model\data]
[2024-03-15 16:34:23,666: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\94b0612e8e834d7ea958090ce6bf29ef\artifacts\model\data\model]
[2024-03-15 16:34:23,666: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\94b0612e8e834d7ea958090ce6bf29ef\artifacts\model\data\model\assets]
[2024-03-15 16:34:23,691: INFO: dir_util: creating C:\Users\USER\Downloads\MLops Projects\Kidney-Disease-Classification\mlruns\0\94b0612e8e834d7ea958090ce6bf29ef\artifacts\model\data\model\variables]
[2024-03-15 16:42:08,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 16:42:08,113: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 16:42:08,120: INFO: common: created directory at: artifacts]
[2024-03-15 16:43:14,792: INFO: common: json file saved at: scores.json]
[2024-03-18 13:18:47,946: INFO: main: *******************]
[2024-03-18 13:18:47,946: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-18 13:18:47,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 13:18:47,963: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 13:18:47,965: INFO: common: created directory at: artifacts]
[2024-03-18 13:19:48,740: INFO: common: json file saved at: scores.json]
[2024-03-18 13:19:48,740: INFO: common: json file saved at: scores.json]
[2024-03-18 13:19:48,746: ERROR: main: 'Evaluation' object has no attribute 'log_into_mlflow']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model_evalution.main()
  File "c:\users\user\downloads\mlops projects\kidney-disease-classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 21, in main
    evaluation.log_into_mlflow()
AttributeError: 'Evaluation' object has no attribute 'log_into_mlflow'
[2024-03-18 13:20:27,085: INFO: main: *******************]
[2024-03-18 13:20:27,100: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-18 13:20:27,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 13:20:27,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 13:20:27,100: INFO: common: created directory at: artifacts]
[2024-03-18 13:21:26,528: INFO: common: json file saved at: scores.json]
[2024-03-18 13:21:26,531: INFO: common: json file saved at: scores.json]
[2024-03-18 13:21:26,533: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-18 16:22:36,654: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion Stage started <<<<<]
[2024-03-18 16:22:36,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 16:22:36,683: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 16:22:36,688: INFO: common: created directory at: artifacts]
[2024-03-18 16:22:36,694: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-18 16:22:36,696: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file (zip_download_dir)]
[2024-03-18 16:25:01,572: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing into file artifacts/data_ingestion/data.rar]
[2024-03-18 16:25:04,236: INFO: stage_01_data_ingestion: >>>>> stage Data Ingestion Stage completed <<<<<

x=========x]
[2024-03-18 16:25:47,060: INFO: stage_02_prepare_base_model: ***************]
[2024-03-18 16:25:47,060: INFO: stage_02_prepare_base_model: >>>>> stage Prepare Base Model Stage started <<<<<]
[2024-03-18 16:25:47,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 16:25:47,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 16:25:47,077: INFO: common: created directory at: artifacts]
[2024-03-18 16:25:47,079: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-18 16:25:49,125: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-18 16:25:50,021: INFO: stage_02_prepare_base_model: >>>>> stage Prepare Base Model Stage completed <<<<<

x=========x]
[2024-03-18 16:26:09,311: INFO: stage_03_model_training: **************]
[2024-03-18 16:26:09,313: INFO: stage_03_model_training: >>>>>>>> stage Training Stage started <<<<<<<<]
[2024-03-18 16:26:09,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 16:26:09,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 16:26:09,326: INFO: common: created directory at: artifacts]
[2024-03-18 16:26:09,327: INFO: common: created directory at: artifacts\training]
